;;; magit-tbdiff-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from magit-tbdiff.el

(autoload 'magit-tbdiff-ranges "magit-tbdiff" "\
Compare commits in RANGE-A with those in RANGE-B.
$ git range-diff [ARGS...] RANGE-A RANGE-B

(fn RANGE-A RANGE-B &optional ARGS)" t)
(autoload 'magit-tbdiff-revs "magit-tbdiff" "\
Compare commits in REV-B..REV-A with those in REV-A..REV-B.
$ git range-diff [ARGS...] REV-B..REV-A REV-A..REV-B

(fn REV-A REV-B &optional ARGS)" t)
(autoload 'magit-tbdiff-revs-with-base "magit-tbdiff" "\
Compare commits in BASE..REV-A with those in BASE..REV-B.
$ git range-diff [ARGS...] BASE..REV-A BASE..REV-B

(fn REV-A REV-B BASE &optional ARGS)" t)
 (autoload 'magit-tbdiff "magit-tbdiff" nil t)
(eval-after-load 'magit '(progn (transient-append-suffix 'magit-diff "p" '("i" "Interdiffs" magit-tbdiff))))
(register-definition-prefixes "magit-tbdiff" '("magit-tbdiff-"))

;;; End of scraped data

(provide 'magit-tbdiff-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; magit-tbdiff-autoloads.el ends here
