;;; hugsql-ghosts-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from hugsql-ghosts.el

(autoload 'hugsql-ghosts-remove-overlays "hugsql-ghosts" "\
Remove all hugsql ghost overlays from the current buffer." t)
(autoload 'hugsql-ghosts-display-query-ghosts "hugsql-ghosts" "\
Displays an overlay after (hugsql/def-db-fns ...) or (hugsql/def-sqlvec-fns ...) or (conman/bind-connection ...) showing the names and docstrings of the generated functions from that file." t)
(autoload 'hugsql-ghosts-install-hook "hugsql-ghosts" "\
Add a buffer local hook that refreshes the ghosts whenever the cider buffer is reloaded.")
(autoload 'hugsql-ghosts-jump-sql-file "hugsql-ghosts" "\
Jumps to the references SQL file, provides a choice when there are multiple references." t)
(register-definition-prefixes "hugsql-ghosts" '("hugsql-ghosts-"))

;;; End of scraped data

(provide 'hugsql-ghosts-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hugsql-ghosts-autoloads.el ends here
